/******************************************************
 * Processor Module Implementation File.              *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "mips.H"
#include  "mips_isa.cpp"

#include  "mips_syscall.H"

void* mips::dispatch() {
  //!Updating Regs for behavioral simulation.
  if (ac_qk.need_sync()) {
    ac_qk.sync();
  }
  if( ac_pc >= dec_cache_size){
    cerr << "ArchC: Address out of bounds (pc=0x" << hex << ac_pc << ")." << endl;
    stop();
    longjmp(ac_env, AC_ACTION_STOP);
  }
  ac_instr_counter++;
  unsigned ins_id;
  instr_dec = (DEC_CACHE + (ac_pc));
  if ( !instr_dec->valid ){
    unsigned* ins_cache;
    decode_pc = ac_pc;
    quant = 0;
    ins_cache = (ISA.decoder)->Decode(reinterpret_cast<unsigned char*>(buffer), quant);
    instr_dec->valid = true;
    instr_dec->id = ins_cache ? ins_cache[IDENT]: 0;
    instr_dec->end_rot = IntRoutine[instr_dec->id];
    switch (ISA.instr_format_table[instr_dec->id]) {
      case 1:
        instr_dec->F_Type_R.op = ins_cache[1];
        instr_dec->F_Type_R.rs = ins_cache[2];
        instr_dec->F_Type_R.rt = ins_cache[3];
        instr_dec->F_Type_R.rd = ins_cache[4];
        instr_dec->F_Type_R.shamt = ins_cache[5];
        instr_dec->F_Type_R.func = ins_cache[6];
      break;
      case 2:
        instr_dec->F_Type_I.op = ins_cache[1];
        instr_dec->F_Type_I.rs = ins_cache[2];
        instr_dec->F_Type_I.rt = ins_cache[3];
        instr_dec->F_Type_I.imm = ins_cache[7];
      break;
      case 3:
        instr_dec->F_Type_J.op = ins_cache[1];
        instr_dec->F_Type_J.addr = ins_cache[8];
      break;
      case 4:
        instr_dec->F_Type_S.op = ins_cache[1];
        instr_dec->F_Type_S.code = ins_cache[9];
        instr_dec->F_Type_S.func = ins_cache[6];
      break;
      default:
        cerr << "ArchC Error: Unidentified instruction. " << endl;
        cerr << "PC = " << hex << ac_pc << dec << endl;
        stop();
        longjmp(ac_env, AC_ACTION_STOP);
    }
  }
  ins_id = instr_dec->id;

  ISA.cur_instr_id = ins_id;
  return instr_dec->end_rot;
}

void mips::behavior() {

  void* vet[] = {&&I_Init, &&I_lb, &&I_lbu, &&I_lh, &&I_lhu, 
              &&I_lw, &&I_lwl, &&I_lwr, &&I_sb, &&I_sh, 
              &&I_sw, &&I_swl, &&I_swr, &&I_addi, &&I_addiu, 
              &&I_slti, &&I_sltiu, &&I_andi, &&I_ori, &&I_xori, 
              &&I_lui, &&I_add, &&I_addu, &&I_sub, &&I_subu, 
              &&I_slt, &&I_sltu, &&I_instr_and, &&I_instr_or, &&I_instr_xor, 
              &&I_instr_nor, &&I_nop, &&I_sll, &&I_srl, &&I_sra, 
              &&I_sllv, &&I_srlv, &&I_srav, &&I_mult, &&I_multu, 
              &&I_div, &&I_divu, &&I_mfhi, &&I_mthi, &&I_mflo, 
              &&I_mtlo, &&I_j, &&I_jal, &&I_jr, &&I_jalr, 
              &&I_beq, &&I_bne, &&I_blez, &&I_bgtz, &&I_bltz, 
              &&I_bgez, &&I_bltzal, &&I_bgezal, &&I_instr_break, &&I_sys_call, 
              &&I_sync, &&I_teq, &&I_ll, &&I_sc, &&I_movz, 
              &&I_movn, &&I_mul, &&I_clz, &&I_seb, &&I_seh, 
              &&I_ext, &&I_rotr, &&I_rotrv, &&I_absd, &&I_abss, 
              &&I_addd, &&I_adds, &&I_ceqd, &&I_ceqs, &&I_coled, 
              &&I_coles, &&I_coltd, &&I_colts, &&I_cueqd, &&I_cueqs, 
              &&I_culed, &&I_cules, &&I_cultd, &&I_cults, &&I_cund, 
              &&I_cuns, &&I_cvtsd, &&I_cvtds, &&I_cvtdw, &&I_cvtsw, 
              &&I_divd, &&I_divs, &&I_mfc1, &&I_movd, &&I_movs, 
              &&I_muld, &&I_muls, &&I_mtc1, &&I_negd, &&I_negs, 
              &&I_subd, &&I_subs, &&I_truncwd, &&I_truncws, &&I_bc1tl, 
              &&I_bc1t, &&I_bc1f, &&I_bc1fl, &&I_sdc1, &&I_ldc1, 
              &&I_swc1, &&I_lwc1, &&I_sqrtd, &&I_sqrts, &&I_movf, 
              &&I_movt, &&I_maddd, &&I_msubd, &&I_movzd, &&I_movnd, 
              &&I_movtd, &&I_movfd, &&I_madds, &&I_msubs, &&I_movns, 
              &&I_movts, &&I_movfs, &&I_movzs, &&I_mfhc1, &&I_mthc1, 
              &&I_ldxc1, &&I_sdxc1, &&I_lwxc1, &&I_swxc1};

  IntRoutine = vet;

  if (has_delayed_load) {
    DM_mport.load(delayed_load_program);
    ac_pc = ac_start_addr;
    has_delayed_load = false;
  }

  #define AC_SYSC(NAME,LOCATION) \
  instr_dec = (DEC_CACHE + (LOCATION)); \
  instr_dec->valid = true; \
  instr_dec->id = 0; \
  instr_dec->end_rot = &&Sys_##LOCATION;

  #include <ac_syscall.def>
  #undef AC_SYSC

  int action = setjmp(ac_env);
  if (action == AC_ACTION_STOP) return;

  I_Init:
    goto *dispatch();

  #define AC_SYSC(NAME,LOCATION) \
  Sys_##LOCATION: \
    ISA.syscall.NAME(); \
    goto *dispatch();

  #include <ac_syscall.def>
  #undef AC_SYSC

  I_lb: // Instruction lb
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_lb(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_lbu: // Instruction lbu
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_lbu(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_lh: // Instruction lh
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_lh(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_lhu: // Instruction lhu
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_lhu(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_lw: // Instruction lw
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_lw(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_lwl: // Instruction lwl
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_lwl(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_lwr: // Instruction lwr
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_lwr(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_sb: // Instruction sb
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_sb(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_sh: // Instruction sh
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_sh(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_sw: // Instruction sw
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_sw(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_swl: // Instruction swl
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_swl(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_swr: // Instruction swr
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_swr(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_addi: // Instruction addi
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_addi(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_4cycle);
    goto *dispatch();

  I_addiu: // Instruction addiu
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_addiu(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_slti: // Instruction slti
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_slti(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_sltiu: // Instruction sltiu
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_sltiu(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_andi: // Instruction andi
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_andi(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_ori: // Instruction ori
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_ori(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_xori: // Instruction xori
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_xori(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_lui: // Instruction lui
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_lui(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_add: // Instruction add
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_add(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_4cycle);
    goto *dispatch();

  I_addu: // Instruction addu
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_addu(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_4cycle);
    goto *dispatch();

  I_sub: // Instruction sub
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_sub(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_4cycle);
    goto *dispatch();

  I_subu: // Instruction subu
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_subu(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_4cycle);
    goto *dispatch();

  I_slt: // Instruction slt
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_slt(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_sltu: // Instruction sltu
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_sltu(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_instr_and: // Instruction instr_and
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_instr_and(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_instr_or: // Instruction instr_or
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_instr_or(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_instr_xor: // Instruction instr_xor
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_instr_xor(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_instr_nor: // Instruction instr_nor
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_instr_nor(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_nop: // Instruction nop
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_nop(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_sll: // Instruction sll
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_sll(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_srl: // Instruction srl
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_srl(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_sra: // Instruction sra
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_sra(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_sllv: // Instruction sllv
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_sllv(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_srlv: // Instruction srlv
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_srlv(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_srav: // Instruction srav
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_srav(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_mult: // Instruction mult
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_mult(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_4cycle);
    goto *dispatch();

  I_multu: // Instruction multu
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_multu(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_4cycle);
    goto *dispatch();

  I_div: // Instruction div
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_div(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(sc_time(module_period_ns*30, SC_NS));
    goto *dispatch();

  I_divu: // Instruction divu
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_divu(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(sc_time(module_period_ns*30, SC_NS));
    goto *dispatch();

  I_mfhi: // Instruction mfhi
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_mfhi(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_mthi: // Instruction mthi
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_mthi(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_mflo: // Instruction mflo
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_mflo(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_mtlo: // Instruction mtlo
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_mtlo(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_j: // Instruction j
    ISA._behavior_instruction(instr_dec->F_Type_J.op);
    ISA._behavior_mips_Type_J(instr_dec->F_Type_J.op, instr_dec->F_Type_J.addr);
    ISA.behavior_j(instr_dec->F_Type_J.op, instr_dec->F_Type_J.addr);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_jal: // Instruction jal
    ISA._behavior_instruction(instr_dec->F_Type_J.op);
    ISA._behavior_mips_Type_J(instr_dec->F_Type_J.op, instr_dec->F_Type_J.addr);
    ISA.behavior_jal(instr_dec->F_Type_J.op, instr_dec->F_Type_J.addr);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_jr: // Instruction jr
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_jr(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_jalr: // Instruction jalr
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_jalr(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_beq: // Instruction beq
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_beq(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_bne: // Instruction bne
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_bne(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_blez: // Instruction blez
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_blez(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_bgtz: // Instruction bgtz
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_bgtz(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_bltz: // Instruction bltz
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_bltz(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_bgez: // Instruction bgez
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_bgez(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_bltzal: // Instruction bltzal
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_bltzal(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_bgezal: // Instruction bgezal
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_bgezal(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_instr_break: // Instruction instr_break
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_instr_break(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_sys_call: // Instruction sys_call
    ISA._behavior_instruction(instr_dec->F_Type_S.op);
    ISA._behavior_mips_Type_S(instr_dec->F_Type_S.op, instr_dec->F_Type_S.code, instr_dec->F_Type_S.func);
    ISA.behavior_sys_call(instr_dec->F_Type_S.op, instr_dec->F_Type_S.code, instr_dec->F_Type_S.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_sync: // Instruction sync
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_sync(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_teq: // Instruction teq
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_teq(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_ll: // Instruction ll
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_ll(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_sc: // Instruction sc
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_sc(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_movz: // Instruction movz
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_movz(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_movn: // Instruction movn
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_movn(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_mul: // Instruction mul
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_mul(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_clz: // Instruction clz
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_clz(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_seb: // Instruction seb
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_seb(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_seh: // Instruction seh
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_seh(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_ext: // Instruction ext
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_ext(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_rotr: // Instruction rotr
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_rotr(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_rotrv: // Instruction rotrv
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_rotrv(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_absd: // Instruction absd
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_absd(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_abss: // Instruction abss
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_abss(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_addd: // Instruction addd
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_addd(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_adds: // Instruction adds
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_adds(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_ceqd: // Instruction ceqd
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_ceqd(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_ceqs: // Instruction ceqs
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_ceqs(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_coled: // Instruction coled
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_coled(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_coles: // Instruction coles
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_coles(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_coltd: // Instruction coltd
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_coltd(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_colts: // Instruction colts
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_colts(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_cueqd: // Instruction cueqd
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_cueqd(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_cueqs: // Instruction cueqs
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_cueqs(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_culed: // Instruction culed
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_culed(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_cules: // Instruction cules
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_cules(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_cultd: // Instruction cultd
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_cultd(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_cults: // Instruction cults
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_cults(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_cund: // Instruction cund
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_cund(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_cuns: // Instruction cuns
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_cuns(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_cvtsd: // Instruction cvtsd
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_cvtsd(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_cvtds: // Instruction cvtds
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_cvtds(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_cvtdw: // Instruction cvtdw
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_cvtdw(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_cvtsw: // Instruction cvtsw
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_cvtsw(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_divd: // Instruction divd
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_divd(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_divs: // Instruction divs
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_divs(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_mfc1: // Instruction mfc1
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_mfc1(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_movd: // Instruction movd
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_movd(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_movs: // Instruction movs
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_movs(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_muld: // Instruction muld
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_muld(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_muls: // Instruction muls
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_muls(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_mtc1: // Instruction mtc1
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_mtc1(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_negd: // Instruction negd
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_negd(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_negs: // Instruction negs
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_negs(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_subd: // Instruction subd
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_subd(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_subs: // Instruction subs
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_subs(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_truncwd: // Instruction truncwd
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_truncwd(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_truncws: // Instruction truncws
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_truncws(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_bc1tl: // Instruction bc1tl
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_bc1tl(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_bc1t: // Instruction bc1t
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_bc1t(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_bc1f: // Instruction bc1f
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_bc1f(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_bc1fl: // Instruction bc1fl
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_bc1fl(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_sdc1: // Instruction sdc1
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_sdc1(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_ldc1: // Instruction ldc1
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_ldc1(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_swc1: // Instruction swc1
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_swc1(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_lwc1: // Instruction lwc1
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_lwc1(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_sqrtd: // Instruction sqrtd
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_sqrtd(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_sqrts: // Instruction sqrts
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_sqrts(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_movf: // Instruction movf
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_movf(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_movt: // Instruction movt
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_movt(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_maddd: // Instruction maddd
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_maddd(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_msubd: // Instruction msubd
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_msubd(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_movzd: // Instruction movzd
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_movzd(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_movnd: // Instruction movnd
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_movnd(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_movtd: // Instruction movtd
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_movtd(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_movfd: // Instruction movfd
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_movfd(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_madds: // Instruction madds
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_madds(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_msubs: // Instruction msubs
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_msubs(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_movns: // Instruction movns
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_movns(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_movts: // Instruction movts
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_movts(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_movfs: // Instruction movfs
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_movfs(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_movzs: // Instruction movzs
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_movzs(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_mfhc1: // Instruction mfhc1
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_mfhc1(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_mthc1: // Instruction mthc1
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_mthc1(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_ldxc1: // Instruction ldxc1
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_ldxc1(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_sdxc1: // Instruction sdxc1
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_sdxc1(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_lwxc1: // Instruction lwxc1
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_lwxc1(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_swxc1: // Instruction swxc1
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_swxc1(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

} // behavior()

#include <ac_sighandlers.H>
#include <ac_args.H>

void mips::init() {

#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void mips::init(int ac, char *av[]) {

  args_t args = ac_init_args( ac, av);
  set_args(args.size, args.app_args);
  DM_mport.load(args.app_filename);
#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void mips::set_prog_args(){
  ISA.syscall.set_prog_args(argc, argv);
}

//Stop simulation (may receive exit status)
void mips::stop(int status) {
  cerr << endl << "ArchC: -------------------- Simulation Finished --------------------" << endl;
  ISA._behavior_end();
  ac_stop_flag = 1;
  ac_exit_status = status;
  set_stopped();
  longjmp(ac_env, AC_ACTION_STOP);
}

void mips::load(char* program) {
  DM_mport.load(program);
}

void mips::delayed_load(char* program) {
  has_delayed_load = true;
  delayed_load_program = new char[strlen(program)];
  strcpy(delayed_load_program, program);
}

// Returns ac_pc value
unsigned mips::get_ac_pc() {
  return ac_pc;
}

// Assigns value to ac_pc
void mips::set_ac_pc(unsigned int value) {
  ac_pc = value;
}

// Wrapper function to PrintStat().
void mips::PrintStat() {
  ac_arch<mips_parms::ac_word, mips_parms::ac_Hword>::PrintStat();
}

// Assigns value to processor frequency and updates cycle time values
void mips::set_proc_freq(unsigned int proc_freq) {
  ac_module::set_proc_freq(proc_freq);
  time_1cycle=sc_time(1*module_period_ns, SC_NS);
  time_4cycle=sc_time(4*module_period_ns, SC_NS);
}

